//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABusiness
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ABEntities : DbContext
    {
        public ABEntities()
            : base("name=ABEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnimalDetails> AnimalDetails { get; set; }
        public virtual DbSet<AnimalProductTypes> AnimalProductTypes { get; set; }
        public virtual DbSet<Animals> Animals { get; set; }
        public virtual DbSet<AnimalSpecies> AnimalSpecies { get; set; }
        public virtual DbSet<AnimalSpiecesProductTypes> AnimalSpiecesProductTypes { get; set; }
        public virtual DbSet<EntityStatuses> EntityStatuses { get; set; }
        public virtual DbSet<Genders> Genders { get; set; }
        public virtual DbSet<Herds> Herds { get; set; }
        public virtual DbSet<ProductionIntervals> ProductionIntervals { get; set; }
    }
}
