//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABusiness
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animals
    {
        public int AnimalId { get; set; }
        public int AnimalSpiecesId { get; set; }
        public Nullable<int> HerdId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string AccountNum { get; set; }
        public Nullable<int> Sex { get; set; }
        public Nullable<int> Age { get; set; }
        public decimal AgeOnInitInDays { get; set; }
        public System.DateTime InitDate { get; set; }
        public int Status { get; set; }
    
        public virtual AnimalDetails AnimalDetails { get; set; }
        public virtual AnimalSpecies AnimalSpecies { get; set; }
        public virtual EntityStatuses EntityStatuses { get; set; }
        public virtual EntityStatuses EntityStatuses1 { get; set; }
        public virtual Genders Genders { get; set; }
        public virtual Herds Herds { get; set; }

        public Animals()
        {

            this.AnimalSpiecesId = 1;
            this.InitDate = DateTime.Now;
            this.Status = 1;
            this.AgeOnInitInDays = (this.Age.HasValue) ? this.Age.Value : 0;

        }

        public Animals(string name, string sex, string age)
        {
            this.Name = name;
            double lAge;
            if (double.TryParse(age, out lAge))
                this.Age = (int)(lAge * 100);

            if (sex == Common.GendersStatic.Male)
            {
                this.Sex = 1;
            }
            else if (sex == Common.GendersStatic.Female)
            {
                this.Sex = 2;
            }
            this.AnimalSpiecesId = 1;
            this.InitDate = DateTime.Now;
            this.Status = 1;
            this.AgeOnInitInDays = (this.Age.HasValue) ? this.Age.Value : 0;

        }
    }
}
