//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABusiness
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnimalDetails
    {
        public int AnimalsId { get; set; }
        public string Test { get; set; }
    
        public virtual Animals Animals { get; set; }
    }
}
