//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABusiness
{
    using System;
    using System.Collections.Generic;
    
    public partial class Herds
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Herds()
        {
            this.Animals = new HashSet<Animals>();
        }

        public Herds(List<Animals> list)
        {
            this.Animals = new HashSet<Animals>();
            foreach (Animals a in list)
            {
                this.Animals.Add(a);
            }
        }

        public int HerdId { get; set; }
        public int AnimalSpiecesId { get; set; }
        public Nullable<int> OwnerId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Animals> Animals { get; set; }
        public virtual AnimalSpecies AnimalSpecies { get; set; }
        public virtual EntityStatuses EntityStatuses { get; set; }
    }
}
